apiVersion: v2
name: reference
description: Reference Helmize Project
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: helmize
  version: ">=0.0.0-0"
  repository: "file://../../charts/helmize"