---
# Source: reference/templates/deploy.yaml
# File: podinfo/service.yaml
# Checksum 5db5e478ba1b1fb19ae295eaf9c22d60f3642c1ebfaa897884364db8da7c9250
apiVersion: v1
kind: Service
metadata:
  labels:
    custom.label: data
    registy.template: label
  name: frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: frontend
  type: ClusterIP
---
# Source: reference/templates/deploy.yaml
# File: podinfo/deploy.yaml
# Checksum 180fcd1de54e143f1304991d9cf801262001f43287e78734e3b9e1e44dd694a0
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    custom.label: data
    registy.template: label
  name: frontend-test
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9797"
        prometheus.io/scrape: "true"
      labels:
        app: frontend
    spec:
      containers:
      - command:
        - ./podinfo
        - --port=9898
        - --port-metrics=9797
        - --level=info
        - --backend-url=http://backend:9898/echo
        - --cache-server=cache:6379
        env:
        - name: PODINFO_UI_COLOR
          value: '#34577c'
        image: ghcr.io/stefanprodan/podinfo:6.0.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: frontend
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        - containerPort: 9797
          name: http-metrics
          protocol: TCP
        - containerPort: 9999
          name: grpc
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
---
# Source: reference/templates/deploy.yaml
# File: podinfo/hpa.yaml
# Checksum a4084d6037c5c7adf13a47032868d266e16b250100333d0b6ae8eb7760177178
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    custom.label: data
    registy.template: label
  name: frontend
spec:
  maxReplicas: 4
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 99
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
