apiVersion: apps/v1
kind: Deployment
metadata:
  name: nested
spec:
  template:
    spec:
      containers:
      - name: nested
        ports:
        # Injects the base Ports from the existing YAML
        - __inject__
        # Overwrites the map for the port with name 'grpc'
        - name: grpc
          containerPort: 1000
          protocol: TCP
        # Adds an extra port  
        - name: extra_port
          containerPort: 10000
          protocol: TCP
        command:
        # Append command argument to exisiting arguments
        - __inject__
        - --level=info