apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    env: {{ $.value }}
spec:
  template:
    spec:
      containers:
      - name: frontend
        command:
        - __inject__
        - --level=info
