{{- range $f, $d := (fromYaml (include "data" $)).data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-{{ $f }}
data:
  field: {{ $d }}
{{- end }}

{{- define "data" -}}
data: 
  name_1: val_1
  name_2: val_2
  name_3: val_3
{{- end -}}