#
# Reference: https://github.com/helm/chart-testing-action
#
name: Linting and Testing
on:
  pull_request:
    branches:    
      - main
jobs: 
  chart-test:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm-version: [ 'v3.4.2', 'v3.5.4', 'v3.6.3', 'v3.7.1', 'v3.8.2', 'latest' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '${{ matrix.helm-version }}'

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@v2.0.1

      - name: Install Plugins
        run: |
          helm plugin install https://github.com/quintush/helm-unittest > /dev/null 2>&1

      - name: Run chart-testing (lint) Helmize
        run: ct lint --config ./charts/ct.yaml --lint-conf ./charts/lint.yaml

      - name: Run chart-testing (lint) Examples
        run: ct lint --config ./examples/ct.yaml         

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install) Examples
        run: ct install --config ./ct.yaml
        if: steps.list-changed.outputs.changed == 'true'
