apiVersion: v2
name: helmize
description: Go Sprig based deployment engine (GitOps Tool)
type: library
version: "0.1.w"
appVersion: "0.1.0"
home: https://helmize.dev
icon: https://raw.githubusercontent.com/buttahtoast/helmize/main/hugo/icon/icon.png
dependencies:
  - name: library
    version: "3.0.0-rc.3"
    repository: https://buttahtoast.github.io/helm-charts/
keywords:
  - library
  - sprig
  - deploy
maintainers:
  - name: oliverbaehler
    email: oliverbaehler@hotmail.com
annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - "[Feat]: Add $.Train as file context"