apiVersion: v2
name: helmize
description: Go Sprig based deployment engine deployed via Helm
type: library
version: "0.1.0-rc.4"
appVersion: "0.1.0"
home: https://helmize.dev
icon: https://raw.githubusercontent.com/buttahtoast/helmize/main/icon.png
dependencies:
  - name: library
    version: "2.2.3"
    repository: https://buttahtoast.github.io/helm-charts/
keywords:
  - library
  - sprig
  - deploy
maintainers:
  - name: oliverbaehler
    email: oliverbaehler@hotmail.com
annotations:
  artifacthub.io/prerelease: "true"