## Helmize Configuration Values
#  The Values are valid in the values of the parent chart
#  since library charts do not accept any values

## Output Options
#

# -- Enable Summary Output
summary: false

# -- Enable Debug Information for Summary Output
debug: false

## Configuration Options
#

# -- Outputs the Configuration (Only for deploy template)
show_config: false

# -- Configuration Location. You can specify a file path in your chart
# @default -- helmize.yaml
helmize_file: ""

# -- Helmize Configuration
helmize: {}

## Development Options
#

# -- Enable timestamp Output (Measurements)
benchmark: false